---
toname: Journal of Clinical Monitoring and Computing
toaddress: Editorial Board
opening: To the editor, 
closing: Regards,
spacing: 1
output: ConwayLetterTemplate::letter
---

Thank you for allowing us to revise our manuscript for further consideration for publication. Please find our responses to the comments from the reviewers below.

# Additional changes

- Title changed to: "Accuracy and precision of zero-heat-flux temperature measurements with the 3M^TM^ Bair Hugger^TM^ Temperature Monitoring System: A systematic review and meta-analysis"

# Reviewer 1

## General comments

*Without the previous Figure 2, which has been removed likely because it was a 100MB large image instead of a Table, there is no overview table of the included studies present in this paper and the reader has to visit the authors website to obtain this critical piece of information. I don't find this acceptable for a systematic review, as critical pieces are not contained in the publication and the preservation of the website can't be guaranteed.*

Response:

>We have created a table to describe the study characterstics to be included in the main manuscript (Table 2).

*The website seems to be out of sync with the paper, as references [6, 23-37], [26,38], and [39] are indeed 18 studies, but the figure at "Graphical overview of the findings", which shows 16 studies does not agree with the list of references - West 2019 [37] and Iden 2015 [28] are both missing from the plot. Subsequently I question the total numbers of patients and samples in the remainder of the text.*

Response:

>The 'Graphical overview of findings' figures in the website present the results of each meta-analysis that was undertaken. The primary meta-analysis contains 16 studies because Iden and West were not included in this particular meta-analysis, as they did not report results of a comparison between ZHF and core temperature. They used nasopharyngeal or sublingual. With the new Table 2 to be included in the main manuscript, we have included the study characteristics for these two studies though.

## Specific comments

*Abstract, P2, L16: I am not sure if "invasive" is the best word for a nasopharangeal or oropharangeal temperature probe compared to let's say a pulmonary artery blood temperature? Maybe "more invasive"?*

Response:

>Changed to 'more' invasive.

*Introduction, P6, L36: I believe the system is now referred to as the "3M Bair Hugger Temperature Monitoring System", although still widely referred to as SpotOn?*

Response:

>We have made this distinction more clear in the introduction. It now reads:

>"Originally developed in the 1970s, zero-heat-flux technology was recently implemented in the 3M Bair Hugger Temperature Monitoring System (3M, St Paul, MN), as a single-use, disposable sensor. This device was previously known as the SpotOn Temperature Monitoring System. Another device on the market is the T-core sensor from Dräger."

*Methods, P9, L9: While the shiny-based website is really neat, it might be advisable to have the search strategy included as an Appendix to the manuscript to ensure it will remain available in the figure?*

Response:

>Included the search strategy as an appendix for the main manuscript.

*Methods, P11, L40: Could you at least get a DOI to archive the code/files to provide a stable place to refer to when this Github repository becomes unavailable?*

Response:

>The github repo containing data and code has been added to Zenodo to attain a DOI.

*Methods P11, L53 and P12, L7: These are kind of mixing results and methods; which might be okay here, but you might want to provide the references for these studies?*

Response:

>We have now included the refernces.

*Methods, P12, L54: Did you consider to do subgroup analyses by measurement site? (Or by population age - pediatric vs. adult)*

>We did undertake.......

*Results, P13, L20: Please cite all studies used here. Also I am not convinced that a website link to contain one of the key elements for any systematic review: the overview table, is acceptable instead of converting the figure into a table and including it in the paper.*

Response:

>We have created a table to describe the study characterstics to be included in the main manuscript (Table 2). Citations were added to the text.

*Results, P13, L27: These values don't agree with the website. Figure: Participants 827 vs. text: participants 756; also you missed the West 2019 paper here, so this needs updating.*

Response:

>The numbers of participants reported in the manuscript is correct. The study by Boisson et al. (2018) split the analyses in their study into times during surgery where there were 'rapid' core temperature changes and 'slow' core temperature changes. As such, the total number of participants reported in the website (n=827) counted the number of participants in the Boisson et al. (2018) study twice. We added that explanation to the website under the figure. 

*Results, P13, L28: Which 16 studies/8 studies etc?*

Response:

>All studies included in the review have been cited at least once in this introductory paragraph for the results. We believe there is little value in citing each of the studies included in each of the meta-analyses, as this information is better presented in the new Table 2 and in the graphical overview of findings figures in the website. 

*Results, P13, L57: The number of subjects can't be the number of measurements, something went wrong here when updating the paper. (You report n=756 in the abstract.)*

Response:

>Thank you for noticing this mistake. The number of participants in this meta-analysis for the nasopharyngeal subgroup was corrected.

*Results, P14, L15: I point this out in my comment in the introduction, why do you clarify it in the results?*

Response:

>Thank you for the suggestion. We moved the explanation to the introduction.

*Results, P14, L35: Can you at least refer to the supplemental material here, if you are not planning to include the bias assessment in the paper?*

Response:

>We have added one of the risk of bias figures to the manuscript (Figure 2) to show risk of bias judgements for each of the included studies.

*Results, P16, L48: So why are you telling us about it if you then don't report it?*

Response:

>

*Discussion, P19, L14: One would assume that the PICU study (Idei) is also in children, not only Carvalho?*

Response:

>Thank you for noticing this mistake - text has been corrected to 'two studies'.

*Discussion, P19, L43: But isn't clinical utility important? Do you want to elaborate here?*

Response:

>

*References: #5 seems incomplete; #7 seems incomplete; #11 is very incomplete, #21 is incomplete; #27 is incomplete*

Response:

>

*Figure 1: Isn't "2 studies awaiting classification" a bit unusual? - You excluded them as they are available only in abstract form, right?*

Response:

>The studies awaiting classification approach is used by Cochrane. In future updates to the review these studies reported in abstract form may be published and full and we could then include them. 


# Reviewer 2

*This is a timely and really worthwhile meta-analysis. My main concern is that the level of evidence - moderate at best - is insufficient to draw any definitive conclusions about the utility of the method. It is also worth noting that this method is an 'indirect measurement' as opposed to peripheral thermometers which give an 'indirect estimate' i.e. the temperature they display is not the temperature they read (see the latest NICE CG65 for more detail)*

Response:

>

*I would like to see a figure for the proportion of readings within the acceptable range.*

Response:

>Although some (not all) studies may have reported this outcome, we believe the statistical approach we used to combine results from individual studies is a more robust method to estimate the accuracy of this temperature monitoring device. This is because as it is able to account for potentially unadjusted repeated measures estimates as well as incorporate the degree of inconsistency between results and sampling error into the estimates of the population limits of agreement. In addition, the '% within acceptable limits' outcome is not a very useful outcome for application to practice, as one can never know which measurement was within or not within the limits. With the population limits of agreement approach, we can interpret that each measurement taken from one of these devices may be as much as 1 degree higher or lower than 'core' temperature.

*Most of all, I think the best (and only really acceptable) conclusion from this paper would be to define the exact characteristics of a trial which would determine the accuracy of ZF thermometers with a high level of evidence.  I also think that such a trial would need to be carried out for every device separately because there are small but important differences in the construction of each of them.*

Response:

>

*The introduction should be reviewed and made to read more clearly.  Repetition of the word "commonly' in consecutive sentences for example..*

Response:

>We have removed the repetition of the 'commonly' term.

*The description of the mechanism of action of the ZFT does not clearly explain it to someone who doesn't already understand it.*

Response:

>

*13/57 I'm sure there were 109k measurement but there weren't that number of participants*

Response:

>Thank you for noticing this mistake. We have corrected it to the number of participats.





