---
title: ""
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
```{r setup}
library(shiny)
library(shinyLP)
library(shinydashboard)
library(shinydashboardPlus)
library(DT)
library(magrittr)
library(dplyr)
library(robvis)
library(ggprisma) #awconway/ggprisma
library(waiter)
library(gofer)#awconway/gofer
library(forcats)
```

Home 
=======================================================================

### 

```{r}
div(class = "jumbotron", style="background:transparent !important", 
                           h1("Accuracy of zero-heat-flux temperature monitoring"), p("A systematic review and meta-analysis"),
                           p(a(class = "btn btn-primary btn-lg button", id='tabBut', "Click here to access the full review")))
                
```


```{r}
HTML('<div class="row">
  <div class="col-sm-12">
    <div class="col-sm-12">
      <div class="box box-solid bg-black-gradient collapsed-box">
        <div class="box-header">
          <i class="fa fa-info"></i>
          <h3 class="box-title">Information</h3>
          <div class="pull-right box-tools">
            <button class="btn bg-black btn-sm" data-widget="collapse" type="button">
              <i class="fa fa-plus"></i>
            </button>
          </div>
        </div>
        <div class="box-body border-radius-none" id="pLoA" collapsed="TRUE" solidHeader="TRUE">
          <div style="width:100%; height:auto;" class="datatables html-widget html-widget-output">          
          </div>
        </div>
        <div class="box-footer text-black">
                  <p>This webpage contains supplementary information for the systematic review. In the results and data pages, users can select a subset of studies to view. We also provide source documents for the data that were extracted from the study.</p>
        </div>
      </div>
    </div>
  </div>
</div>
')
```

```{r}
HTML('<div class="row">
  <div class="col-sm-12">
    <div class="col-sm-12">
      <div class="box box-solid bg-black-gradient collapsed-box">
        <div class="box-header">
          <i class="fa fa-users"></i>
          <h3 class="box-title">Authors</h3>
          <div class="pull-right box-tools">
            <button class="btn bg-black btn-sm" data-widget="collapse" type="button">
              <i class="fa fa-plus"></i>
            </button>
          </div>
        </div>
        <div class="box-body border-radius-none" id="pLoA" collapsed="TRUE" solidHeader="TRUE">
          <div style="width:100%; height:auto;" class="datatables html-widget html-widget-output">          
          </div>
        </div>
        <div class="box-footer text-black">

 <p><a href="https://www.aaronconway.info"> Aaron Conway </a> (Peter Munk Cardiac Centre, UHN &amp; Lawrence S. Bloomberg Faculty of Nursing, University of Toronto)</p>
  
<p>Megan Bittner  (Lawrence S. Bloomberg Faculty of Nursing, University of Toronto)
  
<p>Dan Phan  (Lawrence S. Bloomberg Faculty of Nursing, University of Toronto)
  
<p>Navpreet Kamboj  (Lawrence S. Bloomberg Faculty of Nursing, University of Toronto)
  
<p>Kristina Chang  (Toronto General Hospital, UHN)
  
<p>Elizabeth Tipton (Dapartment of Statistics, Northwestern University)
  
<p>Matteo Parotto  (Toronto General Hospital, UHN)


        </div>
      </div>
    </div>
  </div>
</div>
')
```

Search Strategy
=======================================================================

###

```{r}
fluidRow(
                boxPlus(
                  title = "Medline Search Strategy",
                  closable = FALSE,
                  status = "black",
                  solidHeader = FALSE,
                  collapsible = TRUE,
                  p("1.	zero-heat flux"),
                  p("2.	zero-flux"),
                  p("3.	1 OR 2"),
                  p("4.	(SpotON) OR (Temple Touch Pro)"),
                  p("5.	3 OR 4"),
                  p("6.	Accuracy OR precision OR reliability OR validity OR validation OR standard deviation"),
                  p("7.	Bias OR mean difference OR limit of agreement OR Bland Altman"),
                  p("8.	6 OR 7"),
                  p("9.	(exp “diagnostic errors” / OR exp “sensitivity and specificity” / OR (accura* OR reliability* OR target* OR utilt* OR discriminat* OR differentiat*)
10.	8 OR 9"),
                  p("11.	5 AND 10")
                ),
                boxPlus(
                  title = "Embase Search Strategy",
                  closable = FALSE,
                  status = "black",
                  solidHeader = FALSE,
                  collapsible = TRUE,
                  p("1.	zero-heat flux"),
                  p("2.	zero-flux"),
                  p("3.	1 OR 2"),
                  p("4.	(SpotON) OR (Temple Touch Pro)"),
                  p("5.	3 OR 4"),
                  p("6.	Accuracy OR precision OR reliability OR validity OR validation OR standard deviation"),
                  p("7.	Bias OR mean difference OR limit of agreement OR Bland Altman"),
                  p("8.	6 OR 7"),
                  p("9.	('diagnostic accuracy'/de OR 'diagnostic test accuracy study'/de OR 'diagnostic error'/exp OR 'diagnostic value'/de OR 'sensitivity and specificity'/de OR 'predictive value'/de OR (accura* OR reliabilit* OR target* OR utilit* OR discriminat* OR differentiat*)"),
                  p("11.	5 AND 10")
                )
)
```

Study selection
==========================

```{r}
  ggprisma::ggprisma(retrieved = 130, included = 16, duplicates = 35, 
                     full_text = 22, wrong_intervention = 4, wrong_comparator = 2,
                     wrong_design = 1, awaiting_classification = 2)
```


Risk of bias
==========================



### Across studies

```{r}
    RoB <- data_core %>%
      dplyr::select(Study, RoB_selection, RoB_spoton, RoB_comparator, RoB_flow) %>%
      dplyr::mutate(RoB_overall = dplyr::if_else(RoB_selection == "low" &
                                     RoB_spoton == "low" &
                                     RoB_comparator == "low" &
                                     RoB_flow == "low", "low", "high"))
    
    RoB[RoB == "unclear"] <- "some concerns"
    
    rob_summary(data = RoB, tool = "QUADAS-2", weighted = FALSE)
```

### Within studies

```{r}
RoB <- data_core %>%
      dplyr::select(Study, RoB_selection, RoB_spoton, RoB_comparator, RoB_flow) %>%
      dplyr::mutate(RoB_overall = dplyr::if_else(RoB_selection == "low" &
                                     RoB_spoton == "low" &
                                     RoB_comparator == "low" &
                                     RoB_flow == "low", "low", "high"))
    
    RoB[RoB == "unclear"] <- "some concerns"
    
    rob_traffic_light(data = RoB, tool = "QUADAS-2")
```

Graphical overview of findings
==================

Column {.tabset}

### Core

```{r}
gofer::gofer(data_core, ma_effect = ma_core$effect_estimate,
                         ma_lower = ma_core$lower_limit, ma_upper = ma_core$upper_limit,
                         grade_rating="Moderate", data_age = data_core_age, 
                         dodge_width = 0.85,
                         measurements_logscale =TRUE)

```




Source data
=================

```{r}
shinyLP::iframe(url_link = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSR9-h4cb4ONj7d5Yw9ksyEysVngocRSrMQ6vVjny-6f-d_0CZlhe3HhNG-zaQSJ6rWpBLCb5mVYcYK/pubhtml?widget=true&amp;headers=false", 
                    height="100%", width="100%")
```

